function p = palette(hflag)
% returns a color palette table with two columns:
%   <color> name and <hex> code for each color
% source: https://htmlcolorcodes.com/color-names/
% Oveis Jamialahmadi, Sahlgrenska Academy, Feb 2022.

if nargin < 1
    hflag = false; % if true, plots colors as well
end

p = array2table(["Coral", "FF7F50"; "OrangeRed", "FF4500"; ...
    "Gold", "FFD700"; "Yellow", "FFFF00"; "Khaki", "F0E68C"; ...
    "DarkKhaki", "BDB76B"; "IndianRed", "CD5C5C"; "Salmon", "FA8072"; ...
    "Red", "FF0000"; "FireBrick", "B22222"; "DarkRed", "8B0000"; ...
    "Pink", "FFC0CB"; "HotPink", "FF69B4"; "DeepPink", "FF1493"; ...
    "Orange", "FFA500"; "Violet", "EE82EE"; "Magenta", "FF00FF"; ...
    "BlueViolet", "8A2BE2"; "DarkOrchid", "9932CC"; "Purple", "800080"; ...
    "Indigo", "4B0082"; "SlateBlue", "6A5ACD"; "MediumSlateBlue", "7B68EE"; ...
    "GreenYellow", "ADFF2F"; "LawnGreen", "7CFC00"; "Lime", "00FF00"; ...
    "LimeGreen", "32CD32"; "SpringGreen", "00FF7F"; "MediumSeaGreen", ...
    "3CB371"; "SeaGreen", "2E8B57"; "Green", "008000"; "YellowGreen", ...
    "9ACD32"; "Olive", "808000"; "DarkCyan", "008B8B"; "Teal", "008080"; ...
    "Cyan", "00FFFF"; "SteelBlue", "4682B4"; "SkyBlue", "87CEEB"; ...
    "DeepSkyBlue", "00BFFF"; "DodgerBlue", "1E90FF"; "RoyalBlue", ...
    "4169E1"; "Blue", "0000FF"; "MediumBlue", "0000CD"; "Navy", ...
    "00008B"; "Bisque", "FFE4C4"; "Wheat", "F5DEB3"; "BurlyWood", ...
    "DEB887"; "Tan", "D2B48C"; "Goldenrod", "DAA520"; "Peru", ...
    "CD853F"; "Chocolate", "D2691E"; "Brown", "A52A2A"; "Maroon", ...
    "800000"; "White", "FFFFFF"; "HoneyDew", "F0FFF0"; "Azure", ...
    "F0FFFF"; "WhiteSmoke", "F5F5F5"; "Beige", "F5F5DC"; "Ivory", ...
    "FFFFF0"; "Linen", "FAF0E6"; "LightGray", "D3D3D3"; "Silver", ...
    "C0C0C0"; "DarkGray", "A9A9A9"; "Gray", "808080"; "SlateGray", ...
    "708090"; "DarkSlateGray", "2F4F4F"; "Black", "000000"], ...
    'VariableNames', ["color", "code"]);
p.code = "#" + p.code;
p.Row = p.color;

if hflag % plot colors
    pc = p;
    pc(pc.color == "Black", :) = []; 
    [X,Y] = ndgrid(1:6, 1:11);
    figure('Name', 'paletteHelp', 'WindowState', 'maximized', 'Color', 'w');
    hold on
    ax = gca;
    for i = 1:height(pc)
        % scatter(gca, X(i), Y(i), 200,'filled', 'MarkerFaceColor', pc.code(i))
        plot(gca, X(i), Y(i), 'Marker', 'O', ...
            'MarkerFaceColor', pc.code(i), 'MarkerSize', 30)
        text(ax, X(i), Y(i), pc.color(i), ...
            'VerticalAlignment', 'middle', ...
            'HorizontalAlignment', 'center');
    end
    hold off
    axis(ax, 'square')
    ax.XAxis.Visible = 'off';
    ax.YAxis.Visible = 'off';
 
end
end % END